### PR TITLE
Fix Line Height and Color Regressions

### LINKED ISSUE #260: Dark-mode CSS update changes layout
The CSS changes that came over with the Dark Mode update have also apparently affected page layout. I've asked for details about browser and OS.

https://mltshp.com/p/1JY8D
https://mltshp.com/p/1JY8F
https://mltshp.com/p/1JY8G

### PR DESCRIPTION
**Pull request by spaceninja**
## Overview

This PR fixes a small set of regressions from the recent dark mode css
refactor that resulted in increased line height and a lighter color for
post comments and descriptions.

## Testing

These changes don't show up in screenshots very well. Instead, try comparing the preview deploy version of the following pages to their production versions:

- [Permalink page](https://deploy-preview-271--mltshp-patterns.netlify.app/?path=/story/legacy-areas-permalink--lengthy-content) (preview)
- [Permalink page](https://mltshp.com/p/1BG3N) (production)

- [List page](https://deploy-preview-271--mltshp-patterns.netlify.app/?path=/story/legacy-components-image--lengthy-content) (preview)
- [List page](https://mltshp.com/long-names-like-Llanfairp) (production)

Be sure to review in both light and dark mode!

---

- Fixes #260

### CODE REVIEW

**Comment by jessamynwest** [comment]
1. I don't have dark mode so I am not checking in that. I am sure it's fine.
2. I am not sure if this is helpful but... comments on both preview AND production permalinking seem fine (generally right size, line height is fine) whereas comments on both preview AND production line height examples seem too small/light. I'm pretty sure this is not what I am supposed to be seeing, so I am not sure how to resolve/explain that.

I'm sorry to be making such a THING about this but the smaller (or lighter? or both?) font is just over the "this is too small" line for me, whereas it was fine before. I am AOK with any changes that help people use Dark Mode usefully but the smaller font is too small. I am sorry, I know you are working hard on this.

**Comment by spaceninja** [comment]
The font size on the comments on list view is small, yes, but it's the same size it was before (none of the font sizes changed, just line height and in the case of the text description, the color).

As for the lightness, I'm not sure what you're seeing — the comments are all using the same color they had before the refactor — `#333` (well, technically `rgba(0,0,0,0.8)`, but those are effectively identical on a white background).

**Comment by spaceninja** [comment]
FWIW we have a long-standing issue (#243) from @bradchoate about the font size of the comments.

Why don't I bump the list view comments up from 12px to 14px and see how that feels.

**Comment by jessamynwest** [comment]
I think this is AOK and ready for prime time. Anything else you need from me?

**Comment by spaceninja** [comment]
Thanks @jessamynwest!

**Pull request merged**
